server:
    port: 8081
spring:
    application:
        name: ibiradoptaUserService
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8080/realms/ibiradopta

ibiradopta:
    keycloak:
        serverUrl: http://localhost:8080
        realm: ibiradopta
        clientId: ibiradopta-users-client
        clientSecret: jNrnoiTWAtI7f6C72DQF90YiXmj6hIrS

