spring:
  security:
    oauth2:
      client:
        provider:
          api-gateway-service:
            issuer-uri: ${ISSUER_URI}
        registration:
          api-gateway-service:
            provider: api-gateway-service
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URI}
            scope: openid
  cloud:
    gateway:
      default-filters:
#        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: users-service
          uri: ${USERS_SERVICE_URI}
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=0
            - TokenRelay
        - id: projects-service
          uri: ${PROJECTS_SERVICE_URI}
          predicates:
            - Path=/projects/**
          filters:
            - StripPrefix=0
            - TokenRelay
        - id: payments-service
          uri: ${PAYMENTS_SERVICE_URI}
          predicates:
            - Path=/payments/**
          filters:
            - StripPrefix=0
            - TokenRelay
        - id: mercadopago-service
          uri: ${PAYMENTS_SERVICE_URI}
          predicates:
            - Path=/mercadopago/**
          filters:
            - StripPrefix=0

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config
    oauth:
      clientId: ${SWAGGER_LOGIN_CLIENT_ID}
    urls:
      -   name: gateway-service
          url: /v3/api-docs
#      Definition of the services that will be shown in the Swagger UI
#      user-service Definition
      -   name: users-service
          url: ${SWAGGER_USERS_SERVICE_URI}/users/v3/api-docs
#      project-service Definition
      -   name: projects-service
          url: ${SWAGGER_PROJECTS_SERVICE_URI}/projects/v3/api-docs
