server:
  port: ${PROJECTS_SERVICE_PORT}
spring:
  application:
    name: ibiradoptaProjectService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}