server:
  port: ${PROJECTS_SERVICE_PORT}
spring:
  application:
    name: ibiradoptaProjectService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

springdoc:
  api-docs:
    path: /projects/v3/api-docs
  swagger-ui:
    path: /projects/swagger-ui.html
    oauth:
      clientId: ${SWAGGER_LOGIN_CLIENT_ID}
#    redirectUrl: http://localhost:9090/webjars/swagger-ui/index.html

mercadoPago:
  accessToken: ${MERCADO_PAGO_ACCESS_TOKEN}
  successUrl: ${PAYMENT_SUCCESS_URL}
  failureUrl: ${PAYMENT_FAILURE_URL}

minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucketName: ${MINIO_BUCKET_NAME}
